package form;

import java.io.File;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Lenovo
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }
    private String textCheckSaved = "";
    private boolean saved = true;
    private File file = null;
    boolean inFile = true;
    

    public boolean isInFile() {
        return inFile;
    }

    public void setInFile(boolean isUndo) {
        this.inFile = isUndo;
    }

    public String getTextCheckSaved() {
        return textCheckSaved;
    }

    public void setTextCheckSaved(String textCheckSaved) {
        this.textCheckSaved = textCheckSaved;
    }

    public boolean isSaved() {
        return saved;
    }

    public void setSaved(boolean saved) {
        this.saved = saved;
    }

    public File getFile() {
        return file;
    }

    public void setFile(File file) {
        this.file = file;
    }

    public JMenuItem getjChangeFont() {
        return jChangeFont;
    }

    public void setjChangeFont(JMenuItem jChangeFont) {
        this.jChangeFont = jChangeFont;
    }

    public JMenuItem getjCopy() {
        return jCopy;
    }

    public void setjCopy(JMenuItem jCopy) {
        this.jCopy = jCopy;
    }

    public JMenuItem getjCut() {
        return jCut;
    }

    public void setjCut(JMenuItem jCut) {
        this.jCut = jCut;
    }

    public JMenuItem getjExit() {
        return jExit;
    }

    public void setjExit(JMenuItem jExit) {
        this.jExit = jExit;
    }

    public JMenuItem getjFind() {
        return jFind;
    }

    public void setjFind(JMenuItem jFind) {
        this.jFind = jFind;
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public void setjMenu1(JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    public JMenu getjMenu2() {
        return jMenu2;
    }

    public void setjMenu2(JMenu jMenu2) {
        this.jMenu2 = jMenu2;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JMenuItem getjNew() {
        return jNew;
    }

    public void setjNew(JMenuItem jNew) {
        this.jNew = jNew;
    }

    public JMenuItem getjOpen() {
        return jOpen;
    }

    public void setjOpen(JMenuItem jOpen) {
        this.jOpen = jOpen;
    }

    public JMenuItem getjPaste() {
        return jPaste;
    }

    public void setjPaste(JMenuItem jPaste) {
        this.jPaste = jPaste;
    }

    public JMenuItem getjRedo() {
        return jRedo;
    }

    public void setjRedo(JMenuItem jRedo) {
        this.jRedo = jRedo;
    }

    public JMenuItem getjReplace() {
        return jReplace;
    }

    public void setjReplace(JMenuItem jReplace) {
        this.jReplace = jReplace;
    }

    public JMenuItem getjSave() {
        return jSave;
    }

    public void setjSave(JMenuItem jSave) {
        this.jSave = jSave;
    }

    public JMenuItem getjSaveAs() {
        return jSaveAs;
    }

    public void setjSaveAs(JMenuItem jSaveAs) {
        this.jSaveAs = jSaveAs;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JMenuItem getjSelectAll() {
        return jSelectAll;
    }

    public void setjSelectAll(JMenuItem jSelectAll) {
        this.jSelectAll = jSelectAll;
    }

    public JTextArea getjTextArea1() {
        return jTextArea1;
    }

    public void setjTextArea1(JTextArea jTextArea1) {
        this.jTextArea1 = jTextArea1;
    }

    public JMenuItem getjUndo() {
        return jUndo;
    }

    public void setjUndo(JMenuItem jUndo) {
        this.jUndo = jUndo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jNew = new javax.swing.JMenuItem();
        jOpen = new javax.swing.JMenuItem();
        jSave = new javax.swing.JMenuItem();
        jSaveAs = new javax.swing.JMenuItem();
        jExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jSelectAll = new javax.swing.JMenuItem();
        jCut = new javax.swing.JMenuItem();
        jCopy = new javax.swing.JMenuItem();
        jPaste = new javax.swing.JMenuItem();
        jUndo = new javax.swing.JMenuItem();
        jRedo = new javax.swing.JMenuItem();
        jFind = new javax.swing.JMenuItem();
        jReplace = new javax.swing.JMenuItem();
        jChangeFont = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Text Editor (MTE)");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jMenu1.setText("File");

        jNew.setText("New");
        jMenu1.add(jNew);

        jOpen.setText("Open");
        jMenu1.add(jOpen);

        jSave.setText("Save");
        jMenu1.add(jSave);

        jSaveAs.setText("Save as");
        jMenu1.add(jSaveAs);

        jExit.setText("Exit");
        jMenu1.add(jExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jSelectAll.setText("Select all");
        jMenu2.add(jSelectAll);

        jCut.setText("Cut");
        jMenu2.add(jCut);

        jCopy.setText("Copy");
        jMenu2.add(jCopy);

        jPaste.setText("Paste");
        jMenu2.add(jPaste);

        jUndo.setText("Undo");
        jMenu2.add(jUndo);

        jRedo.setText("Redo");
        jMenu2.add(jRedo);

        jFind.setText("Find");
        jMenu2.add(jFind);

        jReplace.setText("Replace");
        jMenu2.add(jReplace);

        jChangeFont.setText("Change font");
        jMenu2.add(jChangeFont);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jChangeFont;
    private javax.swing.JMenuItem jCopy;
    private javax.swing.JMenuItem jCut;
    private javax.swing.JMenuItem jExit;
    private javax.swing.JMenuItem jFind;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jNew;
    private javax.swing.JMenuItem jOpen;
    private javax.swing.JMenuItem jPaste;
    private javax.swing.JMenuItem jRedo;
    private javax.swing.JMenuItem jReplace;
    private javax.swing.JMenuItem jSave;
    private javax.swing.JMenuItem jSaveAs;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem jSelectAll;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenuItem jUndo;
    // End of variables declaration//GEN-END:variables

}
